"""Apply the SQL files in migrations/ to the database.

Until now there was no runner: the migrations existed as .sql files that
somebody had to remember to paste into psql. Nobody did, so every `tpl_*`
column was missing and the Invoice Appearance screen failed on save with a
raw "column does not exist" from Postgres.

Usage
-----
    python scripts/migrate.py            # apply anything not yet applied
    python scripts/migrate.py --status   # list what is applied, change nothing
    python scripts/migrate.py --force    # re-apply everything, applied or not
    python scripts/migrate.py --print    # print the SQL instead of running it

Connection settings come from the same environment variables app.py uses
(DB_HOST, DB_NAME, DB_USER, DB_PASSWORD, DB_PORT), loaded from .env the same
way -- so run this from whichever shell you start app.py in and there is
nothing extra to configure.

If those are not set in your shell -- they may only exist in your editor's run
configuration -- pass the connection directly instead:

    python scripts/migrate.py --dsn "postgresql://user:pass@localhost:5432/dbname"

Or, with no database access from the command line at all, `--print` writes the
pending SQL to stdout so it can be pasted into pgAdmin. That route skips the
schema_migrations ledger, so a later run will offer the same files again --
harmless, because every migration here is written to be re-runnable.

Safety
------
Each file runs inside its own transaction and is rolled back on failure, so a
broken migration leaves the schema exactly as it was. Applied filenames are
recorded in `schema_migrations`, so running this twice is a no-op -- and the
migrations in this project are written with IF NOT EXISTS anyway, which makes
--force safe as a repair for a ledger that has drifted.
"""

from __future__ import annotations

import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MIGRATIONS = os.path.join(ROOT, "migrations")

sys.path.insert(0, ROOT)

try:
    from dotenv import load_dotenv
    load_dotenv(os.path.join(ROOT, ".env"))
    load_dotenv()
except ImportError:                                      # pragma: no cover
    pass

import psycopg2

LEDGER = """
CREATE TABLE IF NOT EXISTS schema_migrations (
    filename    TEXT PRIMARY KEY,
    applied_at  TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""


def connect(dsn=None):
    if dsn:
        return psycopg2.connect(dsn)
    missing = [name for name in ("DB_HOST", "DB_NAME", "DB_USER")
               if not os.getenv(name)]
    if missing:
        raise SystemExit(
            "Missing database settings: " + ", ".join(missing) + "\n"
            "\nThese normally come from .env or from the shell you start "
            "app.py in.\nIf you cannot get them here, pass the connection "
            "directly:\n"
            "  python scripts/migrate.py --dsn "
            '"postgresql://user:pass@localhost:5432/dbname"\n'
            "\nOr print the SQL and paste it into pgAdmin:\n"
            "  python scripts/migrate.py --print")
    return psycopg2.connect(
        host=os.getenv("DB_HOST"),
        database=os.getenv("DB_NAME"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASSWORD"),
        port=os.getenv("DB_PORT"),
    )


def migration_files():
    if not os.path.isdir(MIGRATIONS):
        raise SystemExit(f"No migrations directory at {MIGRATIONS}")
    # Filenames start with an ISO date, so sorting them is chronological order.
    return sorted(name for name in os.listdir(MIGRATIONS)
                  if name.endswith(".sql"))


def applied_set(conn):
    with conn.cursor() as cur:
        cur.execute(LEDGER)
        conn.commit()
        cur.execute("SELECT filename FROM schema_migrations")
        return {row[0] for row in cur.fetchall()}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--status", action="store_true",
                        help="show what is applied and exit without writing")
    parser.add_argument("--force", action="store_true",
                        help="re-run every migration, applied or not")
    parser.add_argument("--dsn", default=os.getenv("DATABASE_URL"),
                        help="connection string, instead of the DB_* variables")
    parser.add_argument("--print", dest="print_only", action="store_true",
                        help="print the SQL instead of connecting to anything")
    args = parser.parse_args()

    files = migration_files()
    if not files:
        print("No migrations found.")
        return 0

    if args.print_only:
        # No connection at all: this is the route for someone who has pgAdmin
        # open and no credentials on the command line.
        print("-- TaxLinkPro migrations, in order. Safe to re-run.")
        print("-- Generated by scripts/migrate.py --print\n")
        for name in files:
            print(f"\n-- ======== {name} ========")
            with open(os.path.join(MIGRATIONS, name), encoding="utf-8") as handle:
                print(handle.read().rstrip())
        return 0

    conn = connect(args.dsn)
    try:
        done = applied_set(conn)

        if args.status:
            print(f"{len(files)} migration(s) in {MIGRATIONS}\n")
            for name in files:
                print(f"  [{'x' if name in done else ' '}] {name}")
            pending = [n for n in files if n not in done]
            print(f"\n{len(pending)} pending."
                  + (" Run without --status to apply." if pending else ""))
            return 0

        pending = files if args.force else [n for n in files if n not in done]
        if not pending:
            print(f"Up to date -- all {len(files)} migration(s) already applied.")
            return 0

        for name in pending:
            path = os.path.join(MIGRATIONS, name)
            with open(path, encoding="utf-8") as handle:
                sql = handle.read()
            try:
                with conn.cursor() as cur:
                    cur.execute(sql)
                    cur.execute(
                        "INSERT INTO schema_migrations (filename) VALUES (%s) "
                        "ON CONFLICT (filename) DO NOTHING",
                        (name,))
                conn.commit()
                print(f"  applied  {name}")
            except Exception as exc:
                conn.rollback()
                print(f"  FAILED   {name}\n           {exc}", file=sys.stderr)
                print("\nNothing from that file was applied; earlier files "
                      "stay applied.", file=sys.stderr)
                return 1

        print(f"\nDone -- {len(pending)} migration(s) applied.")
        return 0
    finally:
        conn.close()


if __name__ == "__main__":
    raise SystemExit(main())
